SQL:
  Type: Locale
  Host: "localhost"
  Port: "3306"
  Database: "database"
  Username: "root"
  Password: "password"

# Opening a custom gui for books instead of the vanilla mechanic for chiseled bookshelves
ChiseledBookShelfGui:
  Enabled: true
  Title: "Books"
  # The request if the player needs to sneak while opening the gui
  # The opposite means, how the player is able to take books out of the shelf
  SneakingRequired: true
  ActionRequired: RIGHT_CLICK_BLOCK


Storage:
  Enabled:
  # Enables pricing for publishing books. If 'false', the player can publish books for free
  # The pricing can be staged on the amount of pages
  # Requires Vault to be installed
  Pricing:
    Enabled: true
    PageStages:
      25: 250
      50: 500
      75: 750
      100: 1000

  DisplayTitle: "&8Books %name%"
  DateTimeFormat: "dd/MM/yyyy HH:mm:ss"
  ZoneId: "UTC"
  Status:
    True: "&a&l✔"
    False: "&4&l✘"
    Unpublished: "&7Unpublished"
  Icons:
    Folder:
      Material: BOOK
      GenreTitle: "&2&l✦ Genre: &a%genre%"
      Lore: []
    Book:
      Material: "WRITTEN_BOOK"
      Title: "&9Title: &b%title%"
      Lore:
        - "&7Authors: &a%authors%"
        - "&7Published on: &a%date%"
      EditFormat: "&a✎ Shift + Left-Click to edit"
      DeleteFormat: "&4&lX &cShift + Right-Click to delete"


# Prevent players to edit their books once they have published them
PreventReworking: true
PreventReworkingMessage: "&cYou cannot edit this book once it's published!"

