name: Grimoires
version: '${project.version}'
main: net.maksy.grimoires.Grimoires
api-version: '1.20'
softdepend: [Vault, HeadDatabase, ProtocolLib]
commands:
  grimoire:
    description: Use the grimoire plugin
    usage: /grimoire <show|store|read <id> <page>|edit <id> <page>|add <id>|delete <id> <page>|give-editor>
    permission: grimoires.use
    default: true
    aliases: [gri, books]
  bookstore:
    description: Browse and purchase books
    usage: /bookstore
    permission: grimoires.use
    default: true
permissions:
  grimoires.use:
    description: Grants access to basic grimoire commands (show, read, store).
    default: true
  grimoires.admin.edit:
    description: Grants access to grimoire editing commands (edit, add, delete).
    default: op
  grimoires.admin.give-editor:
    description: Grants access to the give-editor command.
    default: op