name: Grimoires
version: '${project.version}'
main: net.maksy.grimoires.Grimoires
api-version: '1.20'
softdepend: [Vault, HeadDatabase]
commands:
  grimoire:
    description: Use the grimoire plugin
    usage: /grimoire
    permission: grimoires.use
    default: true
    aliases: [gri, books]